### ISSUE TITLE
Ionic app content missing

### ISSUE THREAD

**Issue by jdnichollsc** [adnathan/PhoneGapDay#1]
Hi man, I tried to test this demo but I can't

See please: http://screencast.com/t/OHAcPqJy

Thanks in advance!

**Comment by adnathan** [comment]
How did you build/deploy your app?  Did you do "ionic serve" from the command line?  This is needed to bundle up all the Ionic content.

**Comment by LuisMCunha** [comment]
What steps exactly are required to run this app properly?
I opened a terminal and did the following steps:
-npm install
-ionic platform add android
-ionic build android
-ionic run android -l -c -s

When the app opens I only see the tabs, but there is no content and the console displays the following error:
`Uncaught Error: The Ionic app content is missing, http://192.168.240.1:8101/ace.js, Line: 180`

Are there any aditional steps that I need to do?

**Comment by jdnichollsc** [comment]
+1

**Comment by harshvardhan12** [comment]
same is happening for me also...
please provide the necessary steps to build the code and run in mobile
